rtx.zUp = False
rtx.useVertexCapture = False
rtx.camera.lockFreeCamera = False
rtx.ignoreAllVertexColorBakedLighting = True
rtx.vertexColorIsBakedLighting = False
rtx.captureInstances = True
rtx.freeCameraSpeed = 78.4
rtx.legacyMaterial.roughnessConstant = 1
rtx.enableRaytracing = True
rtx.preTransformedVerticesIsUI = True
rtx.uiTextures = 0x0944C7D109FA1E92, 0x12A388FD2A6389D9, 0x1F089EC863831131, 0x4ED39995C4A6D804, 0x89924511336B7D98, 0xA20E4FFE1A1A0C42, 0xA4614779DF4D0E96, 0xA54505AAC08B52D4, 0xDF4706B9BFFB50BE, -0x501DDD59F3AB2565, -0x68A7AD948F3E04C1, -0xE936190D292E4FEB
