rtx.zUp = False
rtx.sceneScale = 0.0025
rtx.useVertexCapture = False
rtx.camera.lockFreeCamera = False
rtx.ignoreAllVertexColorBakedLighting = True
rtx.vertexColorIsBakedLighting = False
rtx.captureInstances = True
rtx.legacyMaterial.roughnessConstant = 1
rtx.enableRaytracing = True
rtx.uniqueObjectDistance = 1
rtx.atmosphere.nightSkyBrightness = 0.004
